var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(c,g,a){if(null==c)throw new TypeError("The 'this' value for String.prototype."+a+" must not be null or undefined");if(g instanceof RegExp)throw new TypeError("First argument to String.prototype."+a+" must not be a regular expression");return c+""};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,g,a){c!=Array.prototype&&c!=Object.prototype&&(c[g]=a.value)};
$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(c,g,a,b){if(g){a=$jscomp.global;c=c.split(".");for(b=0;b<c.length-1;b++){var e=c[b];e in a||(a[e]={});a=a[e]}c=c[c.length-1];b=a[c];g=g(b);g!=b&&null!=g&&$jscomp.defineProperty(a,c,{configurable:!0,writable:!0,value:g})}};
$jscomp.polyfill("String.prototype.startsWith",function(c){return c?c:function(c,a){var b=$jscomp.checkStringArgs(this,c,"startsWith");c+="";for(var e=b.length,f=c.length,m=Math.max(0,Math.min(a|0,b.length)),h=0;h<f&&m<e;)if(b[m++]!=c[h++])return!1;return h>=f}},"es6-impl","es3");
svGlobal.auth=new function(){function c(f){hi5.tool.enableInput();if(f.error)svGlobal.gatewayError(f.name,f.message);else{hi5.$("frmLogin").style.display="none";hi5.$("frmConn").style.display="block";for(var c=hi5.$("programs");c.hasChildNodes();)c.removeChild(c.firstChild);var b=f.servers;if(!f.accessNotInList){var d=hi5.$("anyconn");d&&(d.style.display="none")}d=svGlobal.auth.getUserName(hi5.$("user").value);window.__sparkUser={session:f.session,account:d,gateway:hi5.$("gateway").value,servers:b};
f=b.length;if(!(1>f)){for(var d="",q=0;q<f;q++){var e=b[q].server,n=b[q].id,e=b[q].displayName||n||e,k=b[q].icon;k||(k="rdp32.png");var r=document.createElement("div");r.className="icon";var p=document.createElement("img");p.src=k;p.id=n;p.alt=n;p.title=e;p.style.cursor="pointer";p.onclick=g;r.appendChild(p);r.appendChild(document.createElement("br"));r.appendChild(document.createTextNode(e));c.appendChild(r);hi5.appcfg.startup&&n===hi5.appcfg.startup.server&&(d=n)}!d&&hi5.appcfg.startup&&(console.log("start up:"+
hi5.appcfg.startup.server+" not found, use the first instead"),d=b[0].id);d&&a(d,!hi5.appcfg.startup.newWindow,!0)}}}function g(f){var b=f.target;b.onclick=null;setTimeout(function(){b.onclick=g},300);a(b.id)}function a(a,b,c){var d=window.__sparkUser,f=d.servers,g=f.length;d.server=null;window.sparkGateway=d.gateway;for(var n=0;n<g;n++){var k=f[n];if(a==k.id){k.gateway=d.gateway;k.session=d.session;k.account=d.account;d.server=k;break}}if(d.server){console.log("connecting to:"+d.server.id);(a=hi5.$("touchpad"))&&
a.checked&&(d.server.touchpad=!0);if(a=hi5.$("keyboard"))a=parseInt(a.options[a.selectedIndex].value),0<a&&(d.server.keyboard=a);if(svGlobal.auth.onconnect)svGlobal.auth.onconnect(d.server);a=d.server.rdp&&("app"==d.server.startProgram||d.server.rdp.remoteProgram);void 0==b&&(b=a);if(b){var h=svManager.getInstance();if(a&&h&&h.running())h.startApp(d.server.exe||d.server.rdp.remoteProgram,d.server.args||d.server.rdp.remoteArgs,""),e&&e.visible()&&e.dismiss();else{var m=function(a){function d(){null==
e&&(e=new hi5.ui.Lightbox(hi5.$("login")));e.visible()?e.dismiss():e.show()}var b=a.toolbar.querySelector("#__sv_btn_home");b||(b=a.toolbar.addButton(hi5.appcfg.img.home||"home.png",d),b.id="__sv_btn_home")},h=new Rdp2(d.server);hi5.$("login").style.display="none";var l=new svGlobal.LocalInterface;l.onremoteappicon=function(a,d){if(l.toolbar&&a.isMainWin()&&32==d.getWidth()){var b="win"+a.id;if(!l.toolbar.querySelector("#"+b)){m(l);var c=l.toolbar.addButton(d.getDataURL(),function(){a.activate(1)});
c.id=b;c.title=a.titleInfo;c.style.width="32px";c.style.height="32px";c.addEventListener("mouseover",function(){c.title=a.titleInfo},!1);setTimeout(function(){a.activate(1)},333)}}};l.onremoteappclose=function(a){l.toolbar&&(a=l.toolbar.querySelector("#win"+a.id))&&l.toolbar.removeChild(a)};h.addSurface(l);h.run();h.onclose=function(){if(c){window.__sparkUser=null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none"}else h.hide(),hi5.$("login").style.display=
"block"}}}else b=document.getElementById("multiMon"),d.server.rdp?(b&&b.checked&&(d.server.rdp.multiMon="on"),window.open("rdpdirect.html")):d.server.vnc?window.open("vnc.html"):d.server.ssh?window.open("sshdirect.html"):d.server.telnet&&window.open("telnet.html")}else hi5.notifications.notify("Not a valid server")}var b=this,e=null;this.getLoginURL=function(){return("https:"==location.protocol?"wss://":"ws://")+hi5.$("gateway").value+"/LOGIN?"};this.showLogDlg=function(){window.__sparkUser=null;
var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none";(a=svManager.getInstance())&&a.running()&&a.close()};this.getUserName=function(a){hi5.appcfg&&hi5.appcfg.domain&&(a.toLowerCase().startsWith(hi5.appcfg.domain.toLowerCase()+"\\")||(a=hi5.appcfg.domain+"\\"+a));return a};this.login=function(a){function e(a,d){window.__sparkUser=null;if(!b.beforelogin||!b.beforelogin(a)){hi5.tool.disableInput();var c=new WebSocket(a.substring(0,a.indexOf("?"))+
"?_METHOD=post","login");c.onclose=function(a){h||(hi5.notifications.notify(__svi18n.errorCode.connection),b.showLogDlg());hi5.tool.enableInput();b.afterlogin&&b.afterlogin(h);h=!1};c.onopen=function(a){h=!0};c.onmessage=function(b){0==b.data.indexOf("00")?c.send("00"+a.substring(a.indexOf("?")+1)):(b=JSON.parse(b.data),0===b.type&&(b.message||b.name)?svGlobal.gatewayError(b.name,b.message):(b.error||c.send("A1"+navigator.userAgent),d(b)))}}}var h=!1,d=hi5.browser.cookie2Obj();d.svSession&&d.svEmail&&
(a+="&svSession="+d.svSession+"&svEmail="+encodeURIComponent(d.svEmail));setTimeout(function(){e(a,c)},5);return!1}};
window.addEventListener("load",function(c){function g(){c.preventDefault();svGlobal.auth.beforesubmit&&svGlobal.auth.beforesubmit();var a=hi5.$("frmLogin").elements,b=svGlobal.auth.getUserName(a.user.value),e=a.pwd.value,b=svGlobal.auth.getLoginURL()+"user="+encodeURIComponent(b)+"&pwd="+encodeURIComponent(e);(a=a.sharedSecret)&&a.value&&(b+="&sharedSecret="+encodeURIComponent(a.value));return svGlobal.auth.login(b)}(function(){hi5.$("user").focus();hi5.$("frmLogin").onsubmit=g;var a=hi5.$("anyconn");
a&&(a.onclick=function(){window.open("rdp.html?gateway="+hi5.$("gateway").value)});if(a=document.querySelector('input[name="showlogin"]'))a.onclick=svGlobal.auth.showLogDlg;var a=hi5.browser.cookie2Obj(),b=-1!=document.cookie.indexOf("__SV_TOKEN_A"),c=hi5.tool.queryToObj();if(a.svEmail||a.user||b||c.autoLogin){var f=hi5.$("frmLogin").elements;f.user.value=a.svEmail||a.user||"";f.pwd.value=(a.svSession?"fake":a.pwd)||"_";a.gateway&&(f.gateway.value=a.gateway);(f.user.value&&f.pwd.value||a.autoLogin||
b||c.autoLogin)&&setTimeout(g,30)}var a=hi5.$("settings"),m=hi5.$("settingsDiv");a&&(a.onclick=function(){m&&((new hi5.ui.Lightbox(m)).show(),hi5.$("currPwd").focus())});if(a=hi5.$("frmSettings"))a.onsubmit=function(a){a.preventDefault();var b=a.target.elements;if(b.newPwd1.value!=b.newPwd2.value)hi5.notifications.notify(__svi18n.errorCode.pwdmatch);else{a=svGlobal.auth.getLoginURL()+"_METHOD=post&action=put";var c=new WebSocket(a,"login");c.onmessage=function(a){0==a.data.indexOf("00")?(c.send("00currPwd="+
encodeURIComponent(b.currPwd.value)+"&newPwd="+encodeURIComponent(b.newPwd1.value)+"&user="+encodeURIComponent(svGlobal.auth.getUserName(hi5.$("user").value))),hi5.$("frmSettings").reset()):(a=JSON.parse(a.data),a.error&&svGlobal.gatewayError(a.name,a.message))};m.dismiss&&m.dismiss();return!1}};a=hi5.$("gateway");(b=a.value)||(b=hi5.appcfg.defaultPort?window.location.hostname+":"+hi5.appcfg.defaultPort:window.location.host);0==b.length&&(b="localhost");a.value=b;a=hi5.$("touchpadmode");hi5.browser.isTouch&&
(a.style.display="");(a=hi5.$("user"))&&!a.value&&hi5.appcfg&&hi5.appcfg.domain&&!hi5.appcfg.hiddenDomain&&(a.value=hi5.appcfg.domain+"\\");(function(){var a=!1,b="";try{document.createElement("canvas").getContext("2d"),a=!0}catch(k){b="This browser does not support Canvas.\n\n"}var c=!("WebSocket"in window)&&!("MozWebSocket"in window),e=navigator.userAgent,f=-1!=e.indexOf("Firefox");c&&(b+="This browser doesn't support WebSocket.\n\n",f?b+="Please update to Firefox 6 or later.\n\n":-1!=e.indexOf("Opera")?
b+="Please open 'opera:config#Enable WebSockets' (type it in the link field) make 'Enable WebSockets' selected and restart Opera.\n\n":-1!=e.indexOf("MSIE")&&(b+="Please install Google Chrome Frame.\n\n"));0<b.length&&hi5.notifications.notify(b);return!c&&a})();(a=hi5.$("defPort"))&&hi5.appcfg.defaultPort&&(a.innerHTML=hi5.appcfg.defaultPort);(a=document.getElementById("frmConn"))&&(a=a.querySelector('select[name="keyboard"]'));a&&(b=svGlobal.Rdp.languageToKeyboard.detect())&&(a.value=b)})()},!1);
