/* $Id$ */
(function(){
    jQuery.fn.dashboard = function(options){
      jQuery.noConflict(); /* to prevent $ conflict */
      
      options = jQuery.extend(true, {
          "namespace": "", //No I18N
          "defaultWidgets" : null, /* default configuration for the default widgets */ //No I18N
          "externalWidgets": null, //No I18N
          /* by default, no external widgets are added. When the technician adds widgets, this array is populated */
          "extUrlInfo": null, //No I18N
          "autogenerateDataOnNull": null, //No I18N
          "numberOfRows": 15, //No I18N
          "numberOfColumns": 4 //No I18N
      }, options);
      var db = this; /* jQuery object on which this plugin is called. Will be referred to as "db" subsequently in this documentation*/
      var parent = jQuery(this).parent(); /* jQuery parent of "db" */

      var gridster; /* gridster object that will take care of widget actions */
      var isWidthSet = false;
      var CONSTANTS = jQuery.extend({
          MARGIN: 4,
          MIN_HEIGHT: 133
      },options.CONSTANTS,true);
      var containerWidthDefaults = {
          "wide" : "100%", //NO I18N
          "boxed" : 1328 //NO I18N
      };
      var containerWidth ;

      jQuery(this).addClass("gridster"); /* the developer need not provide "gridster" class to "db". The plugin adds it. */ //No I18N

      function customiwid(el, b, c) {
          jQuery.each(el,function(k,a){
                if (jQuery(a).find('div.widget-summaryrequests-list').hasClass('widget-helpservice-req')) { //No I18N
                    if (jQuery(a).height() > CONSTANTS.MIN_HEIGHT) {
                        jQuery(a).find('div.widget-summaryrequests-list').addClass('widget-helpservicereq'); //No I18N
                        // jQuery('.widget-helpservice-req .row .widget-apprlistcnt-col').css('width','100%'); //No I18N
                    }
                    else {
                        jQuery(a).find('div.widget-summaryrequests-list').removeClass('widget-helpservicereq'); //No I18N
                        // jQuery('.widget-helpservice-req .row .widget-apprlistcnt-col').css('width','50%'); //No I18N
                    }
                }
                if (jQuery(a).find('div.widget-summaryrequests-list').hasClass('widget-helpservice-req')) { //No I18N
                    if (jQuery(a).height() > CONSTANTS.MIN_HEIGHT) {
                        jQuery(a).find('div.widget-summaryrequests-list').addClass('widget-helpservicereq'); //No I18N
                    }
                    else {
                        jQuery(a).find('div.widget-summaryrequests-list').removeClass('widget-helpservicereq'); //No I18N
                    }
                }
                if (jQuery(a).find(' > div.widget-bg').hasClass('widget-summarypendingrequests-bg')) { //No I18N
                    if (jQuery(a).width() > 500) {
                        jQuery(a).find(' > div.widget-summarypendingrequests-bg').addClass('widget-summarypendingrequests'); //No I18N
                        jQuery(a).find(' > div.widget-summarypendingrequests-bg .widget-apprlistcnt').css('width',(100/ jQuery(a).find(".widget-apprlistcnt").length)+"%"); //No I18N
                        jQuery(a).find(' > div.widget-summarypendingrequests-bg .widget-apprlistcnt').css('height',"100%"); //No I18N
                    } else {
                        jQuery(a).find(' > div.widget-summarypendingrequests-bg').removeClass('widget-summarypendingrequests'); //No I18N
                        jQuery(a).find(' > div.widget-summarypendingrequests-bg .widget-apprlistcnt').css('width',''); //No I18N
                    }
                }
				if (jQuery(a).find('.ssp-wrapper').hasClass('code-preview')) { 
					sspsearchtemplate();/*search template ssp call*/
				}
                if (jQuery(a).find(' > div.widget-bg').hasClass('widget-approvalpendingrequests-bg')) { //No I18N
                    // if (jQuery(a).width() > 460 && jQuery(a).width() <= 799) {
                    //     var width = 100/jQuery(a).find(".widget-apprlistcnt").length;
                    //     jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt').removeAttr('style'); //No I18N
                    //     jQuery(a).find(' > div.widget-approvalpendingrequests-bg').addClass('widget-summarypendingrequests'); //No I18N
                    //     jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt').css("width",50+"%"); //No I18N
                    //     jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt:last-child').css("width",100+"%"); //No I18N
                    //     jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt:last-child').css("border-top","1px solid #E8E8E8"); //No I18N
                    // } else if (jQuery(a).width() >= 800) {
                    //     var width = 100/jQuery(a).find(".widget-apprlistcnt").length;
                    //     jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt').removeAttr('style'); //No I18N
                    //     jQuery(a).find(' > div.widget-approvalpendingrequests-bg').addClass('widget-summarypendingrequests'); //No I18N
                    //     jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt').css("width",width+"%"); //No I18N
                    // }
                    // else {
                    //     jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt').removeAttr('style'); //No I18N
                    //     jQuery(a).find(' > div.widget-approvalpendingrequests-bg').removeClass('widget-summarypendingrequests'); //No I18N
                    //     jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt').css("width",""); //No I18N
                    // }
                    if (jQuery(a).width() > 700) {
                        var width = 100/jQuery(a).find(".widget-apprlistcnt").length;
                       // jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt').removeAttr('style'); //No I18N
                        jQuery(a).find(' > div.widget-approvalpendingrequests-bg').addClass('widget-summarypendingrequests'); //No I18N
                        //jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt').css("width",width+"%"); //No I18N
                    }
                    else {
                       // jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt').removeAttr('style'); //No I18N
                        jQuery(a).find(' > div.widget-approvalpendingrequests-bg').removeClass('widget-summarypendingrequests'); //No I18N
                       // jQuery(a).find(' > div.widget-approvalpendingrequests-bg .widget-apprlistcnt').css("width",""); //No I18N
                    }
                }
                if (jQuery(a).find('div.widget-summaryrequests-list').hasClass('widget-portalrequests-list')) { //No I18N
                    var $portal_usage = jQuery("li[data-external=false][data-widgetid=6]"); // No I18N
                    $portal_usage.find("iframe").prop("height",parseInt($portal_usage.find('.widget-summaryrequests-list').height() - $portal_usage.find('.widget-summaryrequests-list .widget-poratl-video').outerHeight() - parseInt($portal_usage.find('.widget-summaryrequests-list').css("padding-bottom")) )+"px"); // No I18N
                }
            });
            //setTimeout(function () {
                jQuery(db).find('li[data-external=false] div.widget-summaryrequests-list').getNiceScroll().resize(); //No I18N
            //}, 10);
      }
      function destroyGridster() {
          gridster.destroy();
          gridster = undefined;
          jQuery(db).find("> ul.gridsterul").off(); //No I18N
          parent.find(".gs-w").removeData("coords"); //No I18N
      }

      function enableGridster() {
            containerWidth = parent.outerWidth() - (2*CONSTANTS.MARGIN);
            /* if(!options.isWideLayout) {
                containerWidth = containerWidthDefaults.boxed - (2*CONSTANTS.MARGIN) - (parseInt(jQuery('.content-panel-inner').css('border-right-width')) + parseInt(jQuery('.content-panel-inner').css('border-left-width')));
            } */
            var numberOfRows = options.numberOfRows;
            var numberOfColumns = options.numberOfColumns;
            var margin = CONSTANTS.MARGIN;
            if (gridster) {
                destroyGridster();
            }
            // if (!isWidthSet) {
            //     containerWidth = containerWidth - margin;
            //     isWidthSet = true;
            // }

            jQuery(db).css({
                "width": containerWidth //No I18N
                // "margin": margin + "px auto" //No I18N
            });
            
            var min_width = ((containerWidth - (numberOfColumns * 2 * margin) ) / numberOfColumns);
            // var min_width = ((jQuery(db).width()-margin)/numberOfColumns)-(2*margin);
            var min_height = CONSTANTS.MIN_HEIGHT;
            function generateCSS() {
                var css = ""; //No I18N
                var headerHeight = 45;
                var stylesheetID = options.namespace.substring(1)+"-widget-scroll-css"; //No I18N
                var stylesheet = document.getElementById(stylesheetID); //No I18N
                if (stylesheet) {
                    stylesheet.remove(); //Comment for IE
                }
                var cssElement = document.createElement("style"); //No I18N
                cssElement.setAttribute("id", stylesheetID); //No I18N
                cssElement.setAttribute("type", "text/css"); //No I18N

                for (var i = 1; i <= numberOfRows; i++) {
                    css += options.namespace + " [data-sizey=\"" + i + "\"] .widget-panel {\n\theight:" + ((i * min_height) + ((i - 1) * (2 * margin)) - headerHeight) + "px;overflow-y:auto;\n}\n"; //No I18N
                }
                //css += options.namespace + " .widget-header {\n\theight:" + headerHeight + "px;\n}\n"; //No I18N
                var styles = document.createTextNode(css);
                cssElement.appendChild(styles);
                document.getElementsByTagName("head")[0].appendChild(cssElement); //No I18N
            }
            generateCSS();
            gridster = jQuery(db).find("> ul.gridsterul").gridster({ //No I18N
                namespace: options.namespace,
                resize: {
                    enabled: false
                },
                min_cols: numberOfColumns,
                max_cols: numberOfColumns,
                max_rows: numberOfRows,
                widget_margins: [margin, margin],
                widget_base_dimensions: [min_width, min_height],
                autogenerate_stylesheet: true
            }).data('gridster'); //No I18N
            gridster.disable();
            customiwid(jQuery(db).find(' ul.gridsterul > li'), min_width, min_height); //No I18N
            // gridster.disable_resize();
      }
      function initialiseLayout(){
        if(options.isWideLayout)
        {
          jQuery(db).closest('.content-panel-inner').css({ //No I18N
              "width":containerWidthDefaults.wide //No I18N
          });
        }
        else
        {
          jQuery(db).closest('.content-panel-inner').css({ //No I18N
              "width":containerWidthDefaults.boxed //No I18N
          });
        }
        enableGridster();
      }
      function initialiseBGColor(){
          jQuery(db).closest(".content-panel-inner").addClass("widget-clr"+options.bgColor); //No I18N
      }
      function initialise(){
        /* This function initialises gridster, adds default widget, external widgets etc. */
        jQuery(db).find("> ul.gridsterul > li").addClass("hide"); //No I18N
        jQuery(db).find("> ul.gridsterul").css({ //No I18N
            "-webkit-margin-before": "0px", //No I18N
            "-webkit-margin-after": "0px", //No I18N
            "-webkit-margin-start": "0px", //No I18N
            "-webkit-margin-end": "0px", //No I18N
            "-webkit-padding-start": "0px", //No I18N
            "margin": "0px" //No I18N
        });

        enableGridster();

        jQuery(db).find("> ul.gridsterul > li").removeClass("hide"); //No I18N
    jQuery('.gridsterul').css("min-height",jQuery(window).height() - (jQuery('.topHeaderBG').height() + jQuery('#TopStrip').height()+11)+"px"); //No I18N
      }
    function setGlobalEvents(){
    jQuery(window).on('resize', function (evt) {    
      jQuery(db).css('width', ''); //No I18N
      jQuery(db).find('> ul.gridsterul').css('width', ''); //No I18N
      // containerWidth = jQuery(db).width() - CONSTANTS.MARGIN;
      parent.closest(".content-panel-inner").css("width",""); //No I18N
      containerWidthDefaults.wide = parent.outerWidth();
      if(options.isWideLayout)
      {
        parent.closest(".content-panel-inner").css({ //No I18N
          "width" : containerWidthDefaults.wide //No I18N
        });
      }
      else
      {
        parent.closest(".content-panel-inner").css({ //No I18N
          "width" : containerWidthDefaults.boxed //No I18N
        });   
      }
      enableGridster();
    });
    }
      function boot(){
        jQuery(db).closest(".selfservice-portal").width("100%"); //No I18N
        initialise();    
    setTimeout(function() {
        initialiseLayout();
        setGlobalEvents();
    },1);
        initialiseBGColor();
      }
      boot();
    }

    // Event binding - csp activity
    jQuery('#my_view_link').off().on("click", function(event) { 
        ClientUtil.addUserPersonalization("home_view", {"view": "my_view"}).then(function() { //No I18N
            window.location.href = window.location.href.replace(/view_type=[a-z_]+/, 'view_type=my_view'); //No I18N
        });
    });
    jQuery('#bakcup_approver_btn_link').off().on("click", function (event) { loadHomePageTabContent('backupapprover'); }); //No I18N
    jQuery('[sdpJs="iframeExtWdgt"]').off().on("load", function(event) { if(this.dataset.loadhandler==="true"){setIframeBodyFont(this);} }); //No I18N
  })(jQuery);
